FROM node:22

# Répertoire de travail
WORKDIR /app

# Copier package.json et package-lock.json avant les autres fichiers
COPY package*.json ./

# Installer les dépendances avec npm ci pour plus de sécurité
RUN npm ci

# Copier tout le code source dans le conteneur
COPY . .

# Exposer le port pour le serveur de développement
EXPOSE 3000

# Lancer l'application avec npm start
CMD ["npm", "start"]